//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_AdjustType
    {
        public int AdjustTypeID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsIncrease { get; set; }
    }
}
