//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public S_SubMenu()
        {
            this.S_Product = new HashSet<S_Product>();
        }
    
        public int SubMenuID { get; set; }
        public string Code { get; set; }
        public Nullable<int> SortCode { get; set; }
        public byte[] Photo { get; set; }
        public Nullable<int> MainMenuID { get; set; }
        public string SubMenuName { get; set; }
    
        public virtual S_MainMenu S_MainMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_Product> S_Product { get; set; }
    }
}
