//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Supplier
    {
        public int SupplierID { get; set; }
        public string Code { get; set; }
        public Nullable<int> TownshipID { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> IsCredit { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string SupplierName { get; set; }
    
        public virtual S_Township S_Township { get; set; }
    }
}
