//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_UserRightEntry
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> EntryModuleID { get; set; }
        public Nullable<bool> IsAllow { get; set; }
    
        public virtual S_User S_User { get; set; }
        public virtual Sys_EntryModule Sys_EntryModule { get; set; }
    }
}
