//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_VoucherSetting
    {
        public int ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public byte[] VoucherLogo { get; set; }
        public string HeaderName { get; set; }
        public string HeaderDesp { get; set; }
        public string HeaderPhone { get; set; }
        public string HeaderAddress { get; set; }
        public string OtherHeader1 { get; set; }
        public string OtherHeader2 { get; set; }
        public string FooterMessage1 { get; set; }
        public string FooterMessage2 { get; set; }
        public string FooterMessage3 { get; set; }
    }
}
