//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_VoucherFormat
    {
        public int ID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string PreFormat { get; set; }
        public string MidFormat { get; set; }
        public Nullable<int> PostFormat { get; set; }
    
        public virtual S_Location S_Location { get; set; }
    }
}
