//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_TranID
    {
        public int ID { get; set; }
        public int SaleTranID { get; set; }
        public int SaleOrderTranID { get; set; }
        public int SaleReturnTranID { get; set; }
        public int SaleConsignTranID { get; set; }
        public int PurTranID { get; set; }
        public int PurOrderTranID { get; set; }
        public int PurReturnTranID { get; set; }
        public int PurConsignTranID { get; set; }
    }
}
