//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_AppWord
    {
        public int WordID { get; set; }
        public string English { get; set; }
        public string Myanmar { get; set; }
        public string Chinese { get; set; }
        public string Keyword { get; set; }
    }
}
