//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_EntryModule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_EntryModule()
        {
            this.S_UserRightEntry = new HashSet<S_UserRightEntry>();
        }
    
        public int EntryModuleID { get; set; }
        public Nullable<int> MainModuleID { get; set; }
        public string EntryModuleName { get; set; }
        public Nullable<int> SortCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<S_UserRightEntry> S_UserRightEntry { get; set; }
        public virtual Sys_MainModule Sys_MainModule { get; set; }
    }
}
